version: "{build}"

os: Visual Studio 2017

platform: 
  - Win32
  - x64

environment:
  MSVC_DEFAULT_OPTIONS: ON

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\transwarp

before_build:
  - cmd: cd C:\projects\transwarp
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" ..

build:
  project: C:\projects\transwarp\build\transwarp.sln
  parallel: true

test_script:
  - cmd: cd C:\projects\transwarp\build
  - cmd: ctest --verbose
